// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toqfsasutkckhmeilmok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcWZzYXN1dGtja2htZWlsbW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTU2NTcsImV4cCI6MjA2NjI3MTY1N30.kRiMyrCNiBXvuKyrpdqBfIZ0Nqgo1w4uU8hRVqkenE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);